import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { notificationsApi } from '@/services/api';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from '@/components/ui/table';
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from '@/components/ui/select';
import { RefreshCw, Send, AlertCircle, CheckCircle2, Clock } from 'lucide-react';
import { toast } from 'sonner';
import { format } from 'date-fns';

export default function Notifications() {
    const [page, setPage] = useState(0);
    const [statusFilter, setStatusFilter] = useState<string>('all');
    const limit = 20;
    const queryClient = useQueryClient();

    const { data, isLoading } = useQuery({
        queryKey: ['notifications-log', page, statusFilter],
        queryFn: () => notificationsApi.getLogs(limit, page * limit, statusFilter === 'all' ? undefined : statusFilter),
    });

    const resendMutation = useMutation({
        mutationFn: notificationsApi.resend,
        onSuccess: () => {
            toast.success('Notification resent successfully');
            queryClient.invalidateQueries({ queryKey: ['notifications-log'] });
        },
        onError: (error: any) => {
            toast.error(error.response?.data?.detail || 'Failed to resend notification');
        },
    });

    const getStatusBadge = (status: string) => {
        switch (status) {
            case 'sent':
                return <Badge className="bg-green-500/10 text-green-500 hover:bg-green-500/20 border-green-500/20">Sent</Badge>;
            case 'failed':
                return <Badge className="bg-red-500/10 text-red-500 hover:bg-red-500/20 border-red-500/20">Failed</Badge>;
            default:
                return <Badge variant="secondary">{status}</Badge>;
        }
    };

    const getTypeIcon = (type: string) => {
        switch (type) {
            case 'daily_challenge':
                return <Clock className="h-4 w-4 text-blue-500" />;
            case 'problem_solved':
                return <CheckCircle2 className="h-4 w-4 text-green-500" />;
            case 'streak_at_risk':
                return <AlertCircle className="h-4 w-4 text-orange-500" />;
            default:
                return <AlertCircle className="h-4 w-4 text-gray-500" />;
        }
    };

    return (
        <div className="space-y-6">
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-3xl font-bold gradient-text">System Notifications</h1>
                    <p className="text-muted-foreground mt-1">
                        View and manage system notifications sent to Discord
                    </p>
                </div>
                <Button
                    variant="outline"
                    size="icon"
                    onClick={() => queryClient.invalidateQueries({ queryKey: ['notifications-log'] })}
                >
                    <RefreshCw className="h-4 w-4" />
                </Button>
            </div>

            <Card className="glass">
                <CardHeader>
                    <div className="flex items-center justify-between">
                        <CardTitle>Notification Log</CardTitle>
                        <div className="flex items-center gap-2">
                            <Select value={statusFilter} onValueChange={setStatusFilter}>
                                <SelectTrigger className="w-[150px]">
                                    <SelectValue placeholder="Filter by status" />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="all">All Status</SelectItem>
                                    <SelectItem value="sent">Sent</SelectItem>
                                    <SelectItem value="failed">Failed</SelectItem>
                                    <SelectItem value="pending">Pending</SelectItem>
                                </SelectContent>
                            </Select>
                        </div>
                    </div>
                    <CardDescription>
                        History of all notifications generated by the system
                    </CardDescription>
                </CardHeader>
                <CardContent>
                    {isLoading ? (
                        <div className="flex justify-center py-8">
                            <RefreshCw className="h-8 w-8 animate-spin text-primary" />
                        </div>
                    ) : !data?.notifications.length ? (
                        <div className="text-center py-12 text-muted-foreground">
                            No notifications found
                        </div>
                    ) : (
                        <div className="space-y-4">
                            <div className="rounded-md border">
                                <Table>
                                    <TableHeader>
                                        <TableRow>
                                            <TableHead>Status</TableHead>
                                            <TableHead>Time</TableHead>
                                            <TableHead>Type</TableHead>
                                            <TableHead>Title</TableHead>
                                            <TableHead>Recipient</TableHead>
                                            <TableHead className="text-right">Actions</TableHead>
                                        </TableRow>
                                    </TableHeader>
                                    <TableBody>
                                        {data.notifications.map((notif) => (
                                            <TableRow key={notif.id}>
                                                <TableCell>{getStatusBadge(notif.status)}</TableCell>
                                                <TableCell className="whitespace-nowrap text-muted-foreground text-sm">
                                                    {format(new Date(notif.created_at), 'MMM d, HH:mm')}
                                                </TableCell>
                                                <TableCell>
                                                    <div className="flex items-center gap-2">
                                                        {getTypeIcon(notif.type)}
                                                        <span className="capitalize">{notif.type.replace('_', ' ')}</span>
                                                    </div>
                                                </TableCell>
                                                <TableCell className="font-medium">{notif.title}</TableCell>
                                                <TableCell>{notif.recipient}</TableCell>
                                                <TableCell className="text-right">
                                                    <Button
                                                        variant="ghost"
                                                        size="sm"
                                                        onClick={() => resendMutation.mutate(notif.id)}
                                                        disabled={resendMutation.isPending}
                                                        title="Resend Notification"
                                                    >
                                                        <Send className="h-4 w-4" />
                                                    </Button>
                                                </TableCell>
                                            </TableRow>
                                        ))}
                                    </TableBody>
                                </Table>
                            </div>

                            {/* Pagination */}
                            <div className="flex items-center justify-between">
                                <p className="text-sm text-muted-foreground">
                                    Showing {page * limit + 1} to {Math.min((page + 1) * limit, data.total)} of {data.total} entries
                                </p>
                                <div className="flex gap-2">
                                    <Button
                                        variant="outline"
                                        size="sm"
                                        onClick={() => setPage((p) => Math.max(0, p - 1))}
                                        disabled={page === 0}
                                    >
                                        Previous
                                    </Button>
                                    <Button
                                        variant="outline"
                                        size="sm"
                                        onClick={() => setPage((p) => p + 1)}
                                        disabled={(page + 1) * limit >= data.total}
                                    >
                                        Next
                                    </Button>
                                </div>
                            </div>
                        </div>
                    )}
                </CardContent>
            </Card>
        </div>
    );
}
